/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GetMetrics */

#ifndef _Included_GetMetrics
#define _Included_GetMetrics
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GetMetrics
 * Method:    getCpuUser
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_GetMetrics_getCpuUser
  (JNIEnv *, jobject);

/*
 * Class:     GetMetrics
 * Method:    getCpuSystem
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_GetMetrics_getCpuSystem
  (JNIEnv *, jobject);

/*
 * Class:     GetMetrics
 * Method:    getCpuIdle
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_GetMetrics_getCpuIdle
  (JNIEnv *, jobject);

/*
 * Class:     GetMetrics
 * Method:    getCpuNice
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_GetMetrics_getCpuNice
  (JNIEnv *, jobject);

/*
 * Class:     GetMetrics
 * Method:    getMemResident
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_GetMetrics_getMemResident
  (JNIEnv *, jobject);

/*
 * Class:     GetMetrics
 * Method:    getMemVirtual
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_GetMetrics_getMemVirtual
  (JNIEnv *, jobject);

/*
 * Class:     GetMetrics
 * Method:    getDiskTotal
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_GetMetrics_getDiskTotal
  (JNIEnv *, jobject);

/*
 * Class:     GetMetrics
 * Method:    getDiskUsed
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_GetMetrics_getDiskUsed
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
